---
title: "Skistodiaptomus pallidus Transcriptomics"
author: Nathan Gaffin, Matthew Sasaki
date: last-modified
date-format: "YYYY-MM-DD"
language: 
  title-block-published: "Updated"
toc: true
format:
  html:
    anchor-sections: false
    other-links:
      - text: Project Repo
        href: https://github.com/ZoopEcoEvo
---

## Project Description

This project focuses on both the acclimation rate and capacity of Skistodiaptomus pallidus, a freshwater species of calanoid copepod. This project will take place in two different parts. In the first part we will compare CTmax data of a control group (16C) and a warm group (22C), as well as how this differs between two different populations; Ochsner Pond and Centennial Park. In the second part of this project we will do a transcriptomic analysis of the different populations and temperature treatments and compare the expression and regulation of certain genes by looking at differences in RNA.

## Questions, Objectives, Hypotheses

Questions:
1. How does the magnitude/capacity of acclimation compare across populations?
2. How does the rate of acclimation compare across populations?
3. What is the genetic basis for changes in thermal limits?

Objectives:
1. Compare CTmax between the two treatments and populations to determine the magnitude of acclimation.
2. Track the CTmax over shorter timescales to compare the rate of acclimation between the two populations.
3. Determine relationships between the frequency of certain RNA strands in response to heat acclimation. Refine<<

Hypothesis:
1. The magnitude of acclimation will be higher in the population with a higher annual maximum temperatures.
2. The rate of acclimation will be lower in the population with a higher magnitude of acclimation.
3. We would expect the population with a higher magnitude of acclimation to have a larger change in differentially expressed genes between the two treatments.


## Variable Descriptions

| Variable Name              | Variable Description                  | Response or Explanatory?     | Relevant Question or Objective                                            | Data Type                                  | Units                        | Expected Range                | How are zeros and missing data recorded?     |
|---------|---------|---------|---------|---------|---------|---------|---------|
| CTmax | Critical thermal maxima, the upper thermal limit of an organism, recorded when the animal stops responding to stimuli  | dependent | Question/Objective 1, 2, & 3  | Numeric | degrees C | 25C-45C | "NA" |
| Treatment | Control (16C) or Warm (22C), acclimation temperature for each treatment | independent | Question/Objective 1,2, & 3  | categorical | degrees C |  |  |
| Population | There are two different populations one collected from Ochsner Pond (OP), one collected from Centennial Park (CP) | independent | Question/Objective 1, 2, & 3  | categorical | CP, OP |  |  |
| Tube | Tube (1-12) that is used for each animal in each CTmax assay  |  |  | categorical |  | 1-12 |  |
| Thermometer | Thermometer that is used for recording temperature during each CTmax assay  | |  | Numeric | ID |  |  |
| Water Bath | Water bath that is used as an environment for each CTmax assay  |  | | Numeric | ID | | |
| Start Time | Time that the water heater is plugged in and the experiment is officially started  | independent | Questions 1 & 2 | Numeric | Military time | | |
| Acclimation Day | Day that each dish has been acclimating, day 0 is the day that they are moved to their respective incubators for acclimation  | independent | Question/Objective 1, 2 & 3  | Numeric | Days | 0-7 | |
| Experiment Date | Date that the experiment is conducted  |  |  | Numeric | DD/MM/YYYY | | |
| Experimental Replicate | Replicate that the experiment is occurring  |  |  | Numeric |  | 0-5 |  |


## Study Design

Study Design Follows The Rate Of Acclimation Template

Species: Skistodiaptomus pallidus #Species 
Generation: F>3
Treatments: 16C (Control), 22C (Warm)
Trait Measurement: CTmax
Populations: Oschner Pond (OP), Centennial Park (CP)
Replicates: 3
Animals/dish = 23
Total animals needed = 276 (92/replicate)

1. Animals are collected from field and brought to lab.
2. On setup day 56 adult females are selected from each culture and half of them go in either a control dish or a warm dish with 150mL of DIO and ~0.5mL-1.5mL C. ozolini.
3. By the end of setup there will be four dishes: OP+C, CP+C, OP+W, or CP+W, and each dish will have 23 animals.
Equation used to get # animals/dish: 
Animals/dish = ((# of assays * # of tubes)/# of dishes) + (0.5 * # of assays)
4. After setup each dish is placed into the control incubator overnight, a temperature sensor is also placed in the incubators in a dish was 150mL of water to closely monitor the internal temperatures of the incubators (in the incubator there are two shelves, the temperature treatments are always on the same shelf as one another but alternate every replicate, also the incubator that is used as the control or the warm alternates every replicate).
5. On acclimation day 0, 2-3 animals from each dish are used to run a CTmax assay (input CTmax assay protocol), which animals from which dish go in which tube are randomized using ___
6. After the assay each dish is placed in their respective incubators and the 10 Day ROA schedule below is followed.
7. This is replicated 3 times.
8. For the transcriptomic aspect of this project # adult females will be selected from each culture and evenly split into the same four dishes previously, theses animals will also be acclimated in the same way for 10 days, no assays will be done.
9. The RNA of these individuals will be extracted, processed, and analyzed.


10 Day ROA Schedule:
|Acclimation Day|Setup| 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
|---------------|-----| * | * | * | * |* +|---|---| * |---|---| *  |

Key:
+ = Feed/Water Change | 
* = CTmax measurement

## Statistics

### Data Processing 

You may need to 'clean' the data after collection. This section should describe (and explain the utility of) any planned transformations, filtering, etc.

### Key Summary Statistics

| Summary Statistic    |  Calculated For Which Groups  |
|---------|---------|---------|---------|---------|---------|---------|---------|
| Mean +/- Standard Deviation | CTmax for each treatment + population for each day for each replicate |
| Coefficient of Variation | CTmax for each treatment + population for each day, how it changes over the course of the experiment, how similar rate of acclimation is across individuals in a population |
| Rate
| Magnitude
| RNA related stuff | ... |

### Statistical Tests of Hypotheses

Hypothesis 1:

- How model fit will be evaluated:

Using the package "performance" in R

- Post-hoc tests:

Have magnitude of acclimation estimated for both populations, climate data will be pulled for both sites and then test for a significant difference, if our hypothesis is supported we would expect...


- Caveats/Caution when interpreting results: 

Causality: Significant differences between the CTmax of the two populations would show a correlation between the magnitude of acclimation and the population/sample site but would not show causality since unmeasured factors could influence outcomes. Cannot infer causality with only two populations.

Generation: Both populations have spent enough time in lab conditions that they are >F3, this could effect results, but does not diminish or weaken them, but should be made clear nonetheless. On the other hand the generation time allows us to make conclusions we would not be able to make otherwise had they been directly from the field.

- Handling missing values: 

CTmax: Missing ("NA") CTmax values will not be used for data analyses, CTmax values that are recorded under ~30C will not be used. 

Non-CTmax data: Missing data other than CTmax data will interfere with results if used, so we will not use that either. 


Hypothesis 2:

- How model fit will be evaluated:
- Post-hoc tests:
- Non-standard analyses:
- Caveats/Caution when interpreting results:
- Handling missing values:
- 


Hypothesis 3:

- Tests of assumptions:
- How model fit will be evaluated:
- Post-hoc tests:
- Non-standard analyses:
- Caveats/Caution when interpreting results:
- Handling missing values:


### Alternative Approaches

This section should outline potential alternative approaches that could be needed (e.g. when assumptions of planned analyses are not met).

## Key Figures

This section is relatively speculative. It can, however, be helpful to have a section where you outline the expected tables and figures that might be important to display based on the planned questions, analyses, hypotheses, etc.

Raw data figure: 2 panels one for centennial, and one for oschner to compare treatments within populations (CTmax overtime, mean CTmax per replicate per day) applies to magnitude and rate of reaction

Effect of acclimation: difference between warm acclimation and control per day compared across populations

Potential reaction norm figure comparing the two different warm treatments, mean +/- SE CTmax on last day and first day for both populations and treatments
